import Head from 'next/head'
import React from 'react'

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout = (props: RootLayoutProps) => {
  const { children } = props

  return (
    <main>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='favicon.ico' />
      </Head>
      {children}
    </main>
  )
}

export default RootLayout
