import Head from 'next/head'
import React from 'react'

import { montserrat } from './config'

const RootLayout = (props: { children: React.ReactNode }) => {
  const { children } = props

  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='favicon.ico' />
      </Head>
      <main className={montserrat.className}>{children}</main>
    </>
  )
}

export default RootLayout
