import { Html, Head, Main, NextScript } from 'next/document'

import { ResetStyles } from '@app/styles'

export default function Document() {
  return (
    <Html lang='uk-ua'>
      <ResetStyles />
      <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
